version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: products-api-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: products_api
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - products-api-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: products-api-pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
    networks:
      - products-api-network

networks:
  products-api-network:
    driver: bridge

volumes:
  postgres_data:
